version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase,  on `date`
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase,  on `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/myip