<<<<<<< HEAD
version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/myip
=======
---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - echo "build"
  post_build:
    commands:
      - echo "post_build"
>>>>>>> 6b656c4609126a7cd7a454d90979924a01afc9d6
